# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea9071fd9cc3fe0d971eb4435619024a3fd3ce50b037e01ddfbd3b2b79ddd3017b1725432c6647d0fec5313cb7bcb804755c5f4d56e17c0eff659f46cab7f66

test:
  secret_key_base: dec101f9f2e107694c7f689a4a8f54e0d6ee8e07278db7aa2ede1713d8b5dbc4c0d30c1296e8bbb8fe1d19a11b72edbe3de1201f9dcf3626cdedd2969485bd08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
